### ISSUE TITLE
Gradelew issues

### ISSUE THREAD

**Issue by hdhdn** [aleksilassila/litematica-printer#17]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'litematica-printer-master'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find mixingradle.jar (org.spongepowered:mixingradle:0.6-SNAPSHOT).
     Searched in the following locations:
         http://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.6-SNAPSHOT/mixingradle-0.6-SNAPSHOT.jar
         unsure why this is happening, im trying to get this to work with 1.16.5 but whenever i run gradlew setupDecompWorkspace it does this

**Comment by aleksilassila** [comment]
Why do you need to run gradlew setupDecompWorkspace? Anyways, I haven't built the project on 1.16.5 and for that you might need to update fabric mappings or something. Also judging on your error message the repo might just be down. I'll close this since its been a long time, reopen if you still need help with something
