### ISSUE TITLE
The stick tool for moving schematics or selecting schematics does not work in multiplayer

### ISSUE THREAD

**Issue by Divoret** [aleksilassila/litematica-printer#2]
The stick tool for moving schematics or selecting schematics does not work in multiplayer. It works in singleplayer, but not multiplayer. What's the solution to this problem? :(

**Comment by Divoret** [comment]
Ok, weird thing... The tool works on other servers, but not on one specific server I play on. That's weird... can some sort of custom plugin block litematica from being used?

but that doesn;'t make sense... litematica is client sided, so how? I'm so confused. It works in other servers, but not the server I usually play on

**Comment by aleksilassila** [comment]
It's completely client-sided, so yeah, that's confusing. Anyhow, I haven't touched that stick feature myself, I only added the printer functionality. Try to install the latest version of the original litematica and see if the issue keeps happening. If yes, file a bug report to the original litematica repository that this fork is based on so that they can fix it there. It's also possible that they've already patched this, because I haven't updated this fork with their changes recently. If after all the testing you feel like the issue is *specifically* happening only with this fork, let me know. I'll see what I can do.
