### ISSUE TITLE
Incapable of moving after enabling Printer

### ISSUE THREAD

**Issue by queenzeb** [aleksilassila/litematica-printer#26]
Hi I'm not sure what's the cause of this, but whenever I enable Printer mode it's causes my character to be incapable of moving. It totally freezes me in place even after I disable Printer again. I have to reconnect to be able to move around again. I can still use my inventory freely. So it's just my movement.

Printer version: litematica-printer-1.17-1.7
MaLiLib version: MaLiLib-Fabric-1.17.1
Litematica version: Litematica-Mod-Fabric-1.17.1
(These are all copied names from my mod files to get the correct versions for u)

**Comment by aleksilassila** [comment]
Again won't be able to work on anything for about a month, but will look into this eventually. Do you think you could dig the download link / build version for litematica? You might find it in-game too

**Comment by queenzeb** [comment]
![image](https://user-images.githubusercontent.com/88069289/127782889-04a650a8-d80d-4cb6-8aa2-5e0ba5934079.png)

**Comment by queenzeb** [comment]
That's the litematica build i'm using.

**Comment by Qwaentos** [comment]
That mostly happens when standing on an unprinted block and when you have your delay set very low. You'll either start moving slower and slower until you can't move anymore or you just instantly can't move. I feel like the same type of thing happens when just moving around and printing on low delay; it keeps repeating the last movements pressed and slows down over time until there are no more blocks to print in range.

**Comment by aleksilassila** [comment]
Try raising your print interval. Shouldn't be an issue in the latest version though. Reopen if it persists
