### ISSUE TITLE
Some blocks not placing the correct way

### ISSUE THREAD

**Issue by charliegustard** [aleksilassila/litematica-printer#46]
Thankyou for developing this, it's been a great tool for creating build time-lapses.

The only issue I've encountered is that trap doors, end rods and likely a bunch of other blocks don't face the right way. For example, an end rod that should be placed horizontally will be placed vertically. Likewise, trap doors won't place open, only closed. 

I understand that this is an addition that you have probably just chosen not to implement for whatever reasons.

Since I need this addition added relatively soon I am willing to commission this privately if necessary.
message me here: [@charliecustard_builds](https://www.instagram.com/charliecustard_builds/) or discord: charliecustard#0481

I apologise in advance for submitting this as an issue (as it's more of a request) however I couldn't find a contact for you @aleksilassila

**Comment by aleksilassila** [comment]
Glad to see you've come up with some creative ways to use the tool, and I appreciate the offer. It just doesn't feel right to take money for something that I will do either way, and there's not really a way to speed things up either, since it's all about how much spare time I have. Anyway, now that I have picked up the project again, I will try to get it to a better state than last time. So that would include placing the majority of blocks correctly and in their correct state, and also a couple of other additions. Will try to get that done this week, or then after the holidays.

Cheers

**Comment by aleksilassila** [comment]
3731712a Will be resolved in the next update
